### ISSUE TITLE
不需要指定的证书吗

### ISSUE THREAD

**Issue by firecolen** [jkpang/PPAutoPackageScript#10]
"Cars" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'
不需要指定的证书吗？CODE_SIGN_IDENTITY="" PROVISIONING_PROFILE=""

**Comment by jkpang** [comment]
不需要，证书等信息是在导出plist文件里面
