### ISSUE TITLE
xcode 9 exportArchive failed

### ISSUE THREAD

**Issue by zhaopeng21790** [jkpang/PPAutoPackageScript#11]
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc}

** EXPORT FAILED **

貌似是plist文件好像有问题

**Comment by jkpang** [comment]
解决方案：首先使用Xcode手动导出ipa包，然后将导出包文件夹内的ExportOptions.plist文件修改名称后替换掉PPAutoPackageScript文件夹内你需要的plist文件，最后再重新打包就可以了。如果还不行，就重启下Mac再试
