### ISSUE TITLE
shell 中路径或文件名包含空格的解决方式

### ISSUE THREAD

**Issue by sunimp** [jkpang/PPAutoPackageScript#15]
shell 中的路径或者文件名字包含空格时, 可以通过双层双引号解决, 例如 `scheme_name="my app"`, 引用此变量时通过 `"$scheme_name"` 即可, 例如 `ipa_name="\"$scheme_name\"-v$bundle_version"`
FYI.

**Comment by jkpang** [comment]
666 @oneofai

**Comment by a51095** [comment]
> shell 中的路径或者文件名字包含空格时, 可以通过双层双引号解决, 例如 `scheme_name="my app"`, 引用此变量时通过 `"$scheme_name"` 即可, 例如 `ipa_name="\"$scheme_name\"-v$bundle_version"`
> FYI.

你这个操作，像极了蔡徐坤打篮球⛹，脱裤子放屁。
shell语法中，＝用作赋值时，i=0，两边不能有空格；＝用作比较时，if [ $a = $b ] 一定要有空格

**Comment by sunimp** [comment]
> > shell 中的路径或者文件名字包含空格时, 可以通过双层双引号解决, 例如 `scheme_name="my app"`, 引用此变量时通过 `"$scheme_name"` 即可, 例如 `ipa_name="\"$scheme_name\"-v$bundle_version"`
> > FYI.
> 
> 你这个操作，像极了蔡徐坤打篮球⛹，脱裤子放屁。
> shell语法中，＝用作赋值时，i=0，两边不能有空格；＝用作比较时，if [ $a = $b ] 一定要有空格

看清楚问题再逼逼
