### ISSUE TITLE
如果能加入 自动上传到fir或者蒲公英的话,更好

### ISSUE THREAD

**Issue by RtzX** [jkpang/PPAutoPackageScript#3]

**Comment by RtzX** [comment]
`#!/bin/sh

#pod install --no-repo-update

out_path=`date "+%Y-%m-%d-%H-%M-%S"`

if [ ! -d "./fir_build_ipa" ]; then
mkdir ./fir_build_ipa
fi

mkdir ./fir_build_ipa/$out_path

if [ $# -eq 0 ]
then

fir b ./ -w -S ChatTool -p -T firToken -C Debug -c 发布Debug版本 CODE_SIGN_IDENTITY="iPhone Developer: xxx xxx (xxxxxx)" PROVISIONING_PROFILE=xxxxxxxxxxxxxxxxxxxxxxxx -o ./fir_build_ipa/$out_path
#    exit                     ##不存在退出
else
a=$*
echo $a

fir b ./ -w -S ChatTool -p -T firToken -C Debug -c $a CODE_SIGN_IDENTITY="Phone Developer: xxx xxx (xxxxxx)" PROVISIONING_PROFILE=xxxxxxxxxxxxxxxxxxxxxxxx -o ./fir_build_ipa/$out_path

#    for a in $*             ##存在话，取参数放入a中循环
#    do
#        b=`echo $a|tr [a-z] [A-Z]`    ###将a改成大写
#        echo "CC"$b                       ##拼接成功CCA
#    done
fi`

**Comment by RtzX** [comment]
`
#!/bin/sh

#pod install --no-repo-update

out_path=`date "+%Y-%m-%d-%H-%M-%S"`

if [ ! -d "./fir_build_ipa" ]; then
mkdir ./fir_build_ipa
fi

mkdir ./fir_build_ipa/$out_path

if [ $# -eq 0 ]
then

fir b ./ -w -S 你项目的scheme名称 -p -T firToken -C Debug -c 发布Debug版本 CODE_SIGN_IDENTITY="iPhone Developer: xxx xxx (xxxxxx)" PROVISIONING_PROFILE=xxxxxxxxxxxxxxxxxxxxxxxx -o ./fir_build_ipa/$out_path
#    exit                     ##不存在退出
else
a=$*
echo $a

fir b ./ -w -S 你项目的scheme名称 -p -T firToken -C Debug -c $a CODE_SIGN_IDENTITY="Phone Developer: xxx xxx (xxxxxx)" PROVISIONING_PROFILE=xxxxxxxxxxxxxxxxxxxxxxxx -o ./fir_build_ipa/$out_path

#    for a in $*             ##存在话，取参数放入a中循环
#    do
#        b=`echo $a|tr [a-z] [A-Z]`    ###将a改成大写
#        echo "CC"$b                       ##拼接成功CCA
#    done
fi
`

**Comment by jkpang** [comment]
因为我现在的需求时候把ipa包上传到自己公司的服务器,所以就只写了导出ipa包的部分. 使用脚本上传ipa包到fir或蒲公英网上有很多资料的,其两者的官网也有文档,很简单.只需要配置好对应的账户密码, 把上传ipa的脚本代码写在导出ipa包代码后面就行了 @RtzX

**Comment by RtzX** [comment]
好的 .tks
