### ISSUE TITLE
xcode9 自动打包失败

### ISSUE THREAD

**Issue by czboosj** [jkpang/PPAutoPackageScript#9]
"Error Domain=IDEProvisioningErrorDomain Code=9 \"\"boosjdance.app\" requires a provisioning profile with the Push Notifications feature.\" UserInfo={NSLocalizedDescription=\"boosjdance.app\" requires a provisioning profile with the Push Notifications feature., NSLocalizedRecoverySuggestion=Add a profile to the \"provisioningProfiles\" dictionary in your Export Options property list.}",
    "Error Domain=IDEProvisioningErrorDomain Code=9 \"\"NotificationService.appex\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"NotificationService.appex\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the \"provisioningProfiles\" dictionary in your Export Options property list.}"
)}
error: exportArchive: "boosjdance.app" requires a provisioning profile with the Push Notifications feature.

Error Domain=IDEProvisioningErrorDomain Code=9 ""boosjdance.app" requires a provisioning profile with the Push Notifications feature." UserInfo={NSLocalizedDescription="boosjdance.app" requires a provisioning profile with the Push Notifications feature., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

error: exportArchive: "NotificationService.appex" requires a provisioning profile.

Error Domain=IDEProvisioningErrorDomain Code=9 ""NotificationService.appex" requires a provisioning profile." UserInfo={NSLocalizedDescription="NotificationService.appex" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}

最后一步 导出ipa 失败, xcode9 手动打包 需要手选证书,想知道怎么解决

**Comment by burning-git** [comment]
我也遇到这个问题，请问有解决 办法没？

**Comment by czboosj** [comment]
https://chenzhao.date/2016/11/10/IOS%E8%87%AA%E5%8A%A8%E6%89%93%E5%8C%85%E7%A0%94%E7%A9%B6.html  已解决, 主要方案就是手动导出,后会有个plist 文件, 把bitcode 关闭就可以了

**Comment by ghost** [comment]
我用xcode9打包，报了下面的错：
导出 Crabs_star-v2.2.0.ipa 包失败 😢 😢 😢     
ps:以下类型的错误可以参考对应的链接
  1."error: exportArchive: No applicable devices found." --> 可能是ruby版本过低导致,升级最新版ruby再试,升级方法自行百度/谷歌,GitHub issue: https://github.com/jkpang/PPAutoPackageScript/issues/1#issuecomment-297589697
  2."No valid iOS Distribution signing identities belonging to team 6F4Q87T7VD were found." --> http://fight4j.github.io/2016/11/21/xcodebuild/ 


但是ruby已经是升级过的，自己用证书打包是可以打得，说明应该也不是证书的问题吧，我是照着操作来的，群主知道我错在哪吗？？？谢谢

**Comment by langwnag** [comment]
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" && rvm use system你在终端上输入这个命令就好了，有可能你刚升级完ruby版本，但还不是最新的

**Comment by gdfyj90** [comment]
@mahongy 用了这句话还是失败

**Comment by jkpang** [comment]
解决方案：首先使用Xcode手动导出ipa包，然后将导出包文件夹内的ExportOptions.plist文件修改名称后替换掉PPAutoPackageScript文件夹内你需要的plist文件，最后再重新打包就可以了。如果还不行，就重启下Mac再试
